---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
      - name: login-service
        image: bennycao06/login_service:latest
        ports:
        - containerPort: 5001
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: user1
        - name: MYSQL_PASSWORD
          value: password1
        - name: MYSQL_DATABASE
          value: analytics_data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        imagePullPolicy: Always

---
