apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-service
  template:
    metadata:
      labels:
        app: mongo-service
    spec:
      containers:
      - name: mongo-service
        image: bennycao06/mongo_service:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: adminpassword
        ports:
        - containerPort: 27017
