apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: bennycao06/mysql_db:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: analytics_data
        - name: MYSQL_USER
          value: user1
        - name: MYSQL_PASSWORD
          value: password1
        ports:
        - containerPort: 3306
