apiVersion: v1
kind: Service
metadata:
  name: multi-service-lb
spec:
  type: LoadBalancer
  selector:
    service-group: multi-group
  ports:
    - name: display-service
      protocol: TCP
      port: 5006
      targetPort: 5006
    - name: login-service
      protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: NodePort
  selector:
    app: analytics-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30006
---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  selector:
    app: mongo-service
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30007
