apiVersion: v1
kind: Service
metadata:
  name: display-service
spec:
  selector:
    app: display-service
  ports:
    - protocol: TCP
      port:   5006    # External port
      targetPort: 5006   # Container port
  type: LoadBalancer   # Exposes the service on each Node's IP at a static port
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: LoadBalancer   # Exposes the service on each Node's IP at a static port
  ports:
    - protocol: TCP
      port: 5001   # External port
      targetPort: 5001   # Container port
  selector:
    app: login-service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: NodePort
  selector:
    app: analytics-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30006
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  selector:
    app: mongo-service
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30007
